### ISSUE TITLE
Please add a screen shot and a license file

### ISSUE THREAD

**Issue by unixorn** [tobiaseichert/plankton-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by tobiaseichert** [comment]
Thanks! I've included an appropriate licence file, as well as a screenshot and general usage hints.
